language: node_js
node_js: "stable"
install:
- npm install
before_script: 
- chmod 0777 ./node_modules/.bin/mocha
- psql -c 'create database AuthorsHavenTest;' -U postgres 
script:
- npm test
env:
- NODE_ENV=test
cache:
directories:
  - "node_modules"
branches:
only:
  - feature
after_success:
- npm run coverage
